/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iflytek_iflyos_AlsaCAE */

#ifndef _Included_com_iflytek_iflyos_AlsaCAE
#define _Included_com_iflytek_iflyos_AlsaCAE
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iflytek_iflyos_AlsaCAE
 * Method:    init
 * Signature: (Ljava/lang/String;Lcom/iflytek/iflyos/IListener;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_iflytek_iflyos_AlsaCAE_init
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_iflytek_iflyos_AlsaCAE
 * Method:    destory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_iflytek_iflyos_AlsaCAE_destroy
  (JNIEnv *, jclass);

/*
 * Class:     com_iflytek_iflyos_AlsaCAE
 * Method:    startRecord
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_iflytek_iflyos_AlsaCAE_startRecord
  (JNIEnv *, jclass);

/*
 * Class:     com_iflytek_iflyos_AlsaCAE
 * Method:    stopRecord
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_iflytek_iflyos_AlsaCAE_stopRecord
  (JNIEnv *, jclass);

/*
 * Class:     com_iflytek_iflyos_AlsaCAE
 * Method:    CAEReloadResource
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_iflytek_iflyos_AlsaCAE_CAEReloadResource
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_iflytek_iflyos_AlsaCAE
 * Method:    CAESetRealBeam
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_iflytek_iflyos_AlsaCAE_CAESetRealBeam
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_iflytek_iflyos_AlsaCAE
 * Method:    CAEGetVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_iflytek_iflyos_AlsaCAE_CAEGetVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_iflytek_iflyos_AlsaCAE
 * Method:    CAESetShowLog
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_iflytek_iflyos_AlsaCAE_CAESetShowLog
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_iflytek_iflyos_AlsaCAE
 * Method:    CAEAuth
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_iflytek_iflyos_AlsaCAE_CAEAuth
  (JNIEnv *, jclass, jstring);

JNIEXPORT void JNICALL Java_com_iflytek_iflyos_AlsaCAE_CAEShouldClearAudioBuffer
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
